### ISSUE TITLE
tox fails with python 3.7  ( importing matplotlib )

### ISSUE THREAD

**Issue by skelouse** [skelouse/mlframe#2]
* mlframe version: 0.1.13
* Python version:
* Operating System:

### Description

Issue with importing matplotlib in 3.7

### What I Did

added 3.7 to tox.ini

ran `tox` command

### Error

py37 create: .\mlframe\.tox\py37
py37 installdeps: Jinja2, missingno>=0.4.2, pandas>=1.1.1, numpy>=1.19.1, matplotlib>=3.3.1, seaborn>=0.10.1, statsmodels, scipy>=1.3.1, scikit-learn
py37 inst: .\mlframe\.tox\.tmp\package\1\mlframe-0.1.13.zip
py37 installed: certifi==2020.6.20,cycler==0.10.0,Jinja2==2.11.2,joblib==0.16.0,kiwisolver==1.2.0,MarkupSafe==1.1.1,matplotlib==3.3.2,missingno==0.4.2,mlframe==0.1.13,numpy==1.19.2,pandas==1.1.2,patsy==0.5.1,Pillow==7.2.0,pyparsing==2.4.7,python-dateutil==2.8.1,pytz==2020.1,scikit-learn==0.23.2,scipy==1.5.2,seaborn==0.11.0,six==1.15.0,statsmodels==0.12.0,threadpoolctl==2.1.0
py37 run-test-pre: PYTHONHASHSEED='521'
py37 run-test: commands[0] | python mlframe/test.py
Traceback (most recent call last):
  File "mlframe/test.py", line 4, in <module>
    import mlframe
  File ".\mlframe\mlframe\mlframe.py", line 9, in <module>
    import matplotlib.pyplot as plt
  File ".\mlframe\.tox\py37\lib\site-packages\matplotlib\pyplot.py", line 2336, in <module>
    switch_backend(rcParams["backend"])
  File ".\mlframe\.tox\py37\lib\site-packages\matplotlib\__init__.py", line 703, in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
  File ".\mlframe\.tox\py37\lib\site-packages\matplotlib\pyplot.py", line 256, in switch_backend
    switch_backend(candidate)
  File ".\mlframe\.tox\py37\lib\site-packages\matplotlib\pyplot.py", line 276, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File ".\mlframe\.tox\py37\lib\site-packages\matplotlib\pyplot.py", line 277, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "c:\users\12147\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File ".\mlframe\.tox\py37\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File ".\mlframe\.tox\py37\lib\site-packages\matplotlib\backends\backend_qt5.py", line 16, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File ".\mlframe\.tox\py37\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 11, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File ".\mlframe\.tox\py37\lib\site-packages\matplotlib\backends\qt_compat.py", line 170, in <module>
    _setup()
  File ".\mlframe\.tox\py37\lib\site-packages\matplotlib\backends\qt_compat.py", line 130, in _setup_pyqt4
    _setup_pyqt4_internal(api=2)
  File ".\mlframe\.tox\py37\lib\site-packages\matplotlib\backends\qt_compat.py", line 113, in _setup_pyqt4_internal
    sip.setapi(_sip_api, api)
AttributeError: module 'sip' has no attribute 'setapi'
ERROR: InvocationError for command '.\mlframe\.tox\py37\Scripts\python.EXE' mlframe/test.py (exited with code 1)
________________________________________________________________________________ summary ________________________________________________________________________________ 
  py36: commands succeeded
ERROR:   py37: commands failed

**Comment by bkrishna2006** [comment]
Facing the same exact issue with py37.  Any solution yet please ?

**Comment by skelouse** [comment]
> Facing the same exact issue with py37. Any solution yet please ?

Nope we havn't, sorry!

I believe it's an issue with matplotlib looking for pyqt or matplotlib-base.
